name: json_serialization
version: 0.0.1
description: >-
  TODO
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation:

dev_dependencies:
  build_runner: ^1.1.2
  json_serializable:
    path: ../json_serializable

dependency_overrides:
  json_serializable:
    path: ../json_serializable